use_frameworks!

platform :ios, '10.0'

target 'TrumpVRLive_Example' do
  pod 'TrumpVRLive', :path => '../'

  target 'TrumpVRLive_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
